FROM openjdk:8
COPY target/spring-boot-jwt-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]

#FROM openjdk:8
#COPY target/spring-boot-jwt-1.0-SNAPSHOT.jar spring-boot-jwt-1.0-SNAPSHOT.jar
#EXPOSE 8080
#CMD java -jar spring-boot-jwt-1.0-SNAPSHOT.jar
